// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: context.proto

package mcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

func (x *ContextRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type ContextResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	KubernetesVersion string                 `protobuf:"bytes,1,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	Charts            []*HelmChart           `protobuf:"bytes,2,rep,name=charts,proto3" json:"charts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContextResponse) Reset() {
	*x = ContextResponse{}
	mi := &file_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse) ProtoMessage() {}

func (x *ContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse.ProtoReflect.Descriptor instead.
func (*ContextResponse) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{1}
}

func (x *ContextResponse) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *ContextResponse) GetCharts() []*HelmChart {
	if x != nil {
		return x.Charts
	}
	return nil
}

type HelmChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmChart) Reset() {
	*x = HelmChart{}
	mi := &file_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmChart) ProtoMessage() {}

func (x *HelmChart) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmChart.ProtoReflect.Descriptor instead.
func (*HelmChart) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{2}
}

func (x *HelmChart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmChart) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmChart) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_context_proto protoreflect.FileDescriptor

const file_context_proto_rawDesc = "" +
	"\n" +
	"\rcontext.proto\x12\x03mcp\"3\n" +
	"\x0eContextRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\"h\n" +
	"\x0fContextResponse\x12-\n" +
	"\x12kubernetes_version\x18\x01 \x01(\tR\x11kubernetesVersion\x12&\n" +
	"\x06charts\x18\x02 \x03(\v2\x0e.mcp.HelmChartR\x06charts\"W\n" +
	"\tHelmChart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace2N\n" +
	"\x13ModelContextService\x127\n" +
	"\n" +
	"GetContext\x12\x13.mcp.ContextRequest\x1a\x14.mcp.ContextResponseB\x1bZ\x19mcp_eks_adapter/proto;mcpb\x06proto3"

var (
	file_context_proto_rawDescOnce sync.Once
	file_context_proto_rawDescData []byte
)

func file_context_proto_rawDescGZIP() []byte {
	file_context_proto_rawDescOnce.Do(func() {
		file_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)))
	})
	return file_context_proto_rawDescData
}

var file_context_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_context_proto_goTypes = []any{
	(*ContextRequest)(nil),  // 0: mcp.ContextRequest
	(*ContextResponse)(nil), // 1: mcp.ContextResponse
	(*HelmChart)(nil),       // 2: mcp.HelmChart
}
var file_context_proto_depIdxs = []int32{
	2, // 0: mcp.ContextResponse.charts:type_name -> mcp.HelmChart
	0, // 1: mcp.ModelContextService.GetContext:input_type -> mcp.ContextRequest
	1, // 2: mcp.ModelContextService.GetContext:output_type -> mcp.ContextResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_context_proto_init() }
func file_context_proto_init() {
	if File_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_proto_goTypes,
		DependencyIndexes: file_context_proto_depIdxs,
		MessageInfos:      file_context_proto_msgTypes,
	}.Build()
	File_context_proto = out.File
	file_context_proto_goTypes = nil
	file_context_proto_depIdxs = nil
}
